[package]
name = "files_upload"
version = "0.2.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-multipart = "0.4"
actix-files = "0.6"
futures = "0.3"
uuid = { version = "1", features = ["v4"] }